use dioxus::prelude::*;
use dioxus_i18n::prelude::*;
use unic_langid::langid;

mod components;
#[cfg(target_arch = "wasm32")]
mod fixed_history;
mod layouts;
mod pages;
mod theme;
mod ui;

use layouts::app_layout::AppLayout;
use layouts::docs_layout::DocsLayout;
use layouts::home_layout::HomeLayout;
use pages::block_demo::ComponentBlockDemo;
use pages::component_page::ComponentPageInner;
use pages::home::Home;

#[derive(Copy, Clone, PartialEq)]
pub(crate) enum ComponentType {
    /// Normal componet as default.
    Normal,
    /// Component that render the preview inside an iframe for isolation.
    Block,
}

/// Static metadata for a component — no function pointers.
/// Safe for the shared WASM chunk (doesn't pull in component code).
#[derive(Clone, PartialEq)]
pub(crate) struct ComponentMetadata {
    pub(crate) name: &'static str,
    pub(crate) description: &'static str,
    pub(crate) r#type: ComponentType,
    pub(crate) docs: &'static str,
    pub(crate) api_docs: &'static str,
    pub(crate) component: HighlightedCode,
    pub(crate) style: HighlightedCode,
    pub(crate) variants: &'static [VariantMetadata],
}

/// Metadata for a single variant — no function pointer.
#[derive(Clone, PartialEq)]
pub(crate) struct VariantMetadata {
    pub(crate) name: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rs_highlighted: HighlightedCode,
    pub(crate) css_highlighted: Option<HighlightedCode>,
}

/// A live demo entry passed from generated per-component page functions.
/// Contains the function pointer that pulls in the actual component code.
#[allow(unpredictable_function_pointer_comparisons)]
#[derive(Clone, PartialEq)]
pub(crate) struct DemoEntry {
    pub(crate) name: &'static str,
    pub(crate) component: fn() -> Element,
}

#[derive(Copy, Clone, PartialEq)]
pub(crate) struct HighlightedCode {
    pub(crate) light: &'static str,
    pub(crate) dark: &'static str,
}

// Generated by build.rs: Route enum, per-component page functions, Route impl.
include!(concat!(env!("OUT_DIR"), "/routes.rs"));

// Generated by build.rs: reads DIOXUS_ASSET_ROOT from the build environment.
// Only used on WASM to pass the base path to FixedPrefixHistory.
#[cfg(target_arch = "wasm32")]
include!(concat!(env!("OUT_DIR"), "/base_path.rs"));

fn main() {
    // On WASM, use FixedPrefixHistory to work around a wasm-split bug where
    // format!("/{prefix}") produces an empty string in WebHistory::new_inner().
    #[cfg(target_arch = "wasm32")]
    {
        let bp = BASE_PATH.map(|s| s.to_string());
        let history: std::rc::Rc<dyn dioxus::history::History> =
            std::rc::Rc::new(fixed_history::FixedPrefixHistory::new(bp, true));
        let mut vdom = dioxus_core::VirtualDom::new(App);
        vdom.provide_root_context(history);
        dioxus::web::launch::launch_virtual_dom(vdom, dioxus::web::Config::new());
        return;
    }

    #[allow(unreachable_code)]
    {
        #[allow(unused_mut)]
        let mut builder = dioxus::LaunchBuilder::new().with_cfg(server_only! {
            ServeConfig::builder()
                .incremental(
                    dioxus::server::IncrementalRendererConfig::new()
                        .static_dir(
                            std::env::current_exe()
                                .unwrap()
                                .parent()
                                .unwrap()
                                .join("public")
                        )
                        .clear_cache(false)
                )
                .enable_out_of_order_streaming()
        });
        builder.launch(App);
    }
}

#[component]
fn App() -> Element {
    use_init_i18n(|| {
        I18nConfig::new(langid!("en-US"))
            .with_locale((langid!("en-US"), include_str!("i18n/en-US.ftl")))
            .with_locale((langid!("fr-FR"), include_str!("i18n/fr-FR.ftl")))
            .with_locale((langid!("es-ES"), include_str!("i18n/es-ES.ftl")))
            .with_locale((langid!("de-DE"), include_str!("i18n/de-DE.ftl")))
    });

    rsx! {
        Router::<Route> {}
    }
}

#[cfg(feature = "fullstack")]
#[server(endpoint = "static_routes", output = server_fn::codec::Json)]
async fn static_routes() -> Result<Vec<String>, ServerFnError> {
    let mut routes = vec!["/".to_string()];
    for meta in components::COMPONENT_LIST {
        routes.push(format!("/docs/components/{}", meta.name));
        if meta.r#type == ComponentType::Block {
            for variant in meta.variants {
                routes.push(format!("/component/block/{}/{}", meta.name, variant.name));
            }
        }
    }
    Ok(routes)
}

pub(crate) const THEME_CSS: HighlightedCode = HighlightedCode {
    light: include_str!(concat!(
        env!("OUT_DIR"),
        "/dx-components-theme.css.base16-ocean.light.html"
    )),
    dark: include_str!(concat!(
        env!("OUT_DIR"),
        "/dx-components-theme.css.base16-ocean.dark.html"
    )),
};
